### ISSUE TITLE
ValidationError in case when paymentMethodDetails is not filled

### ISSUE THREAD

**Issue by BohdanLeasoft** [gingerpayments/ginger-php-plugin-sdk#16]
If create order without paymentMethodDetails (`new Transactions(
  new Transaction(
    paymentMethod: $paymentMethod
  )
)`), then appear ValidationError:
 `GingerPluginSdk\Exceptions\APIException: ValidationError(400): [] is not of type 'object' in GingerPluginSdk\Client->sendOrder() (line 305 of modules/contrib/custom_drupal_commerce/vendor/gingerpayments/ginger-plugin-sdk/src/Client.php).`

In class [Transaction](https://github.com/gingerpayments/ginger-php-plugin-sdk/blob/main/src/Entities/Transaction.php) on line 61, paymentMethodDetails are creating even in case when it's NULL. Possible, it could be a reason of this issue. 

Also, in [CreateOrderTest](https://github.com/gingerpayments/ginger-php-plugin-sdk/blob/main/src/Tests/CreateOrderTest.php)  orders tested with paymentMethodDetails, so this issue didn't appear on test stage.

**Comment by tiutiunnykleasoft** [comment]
Resolved `41bd927ef5c5919719658aefea814997d714ff7a`
