### ISSUE TITLE
Exception while getting order from SDK in webhook 

### ISSUE THREAD

**Issue by BohdanLeasoft** [gingerpayments/ginger-php-plugin-sdk#17]
Hi,

I tried get order by id via `$client->getOrder($orderId)`. And I got exception:
`GingerPluginSdk\Exceptions\OutOfEnumException: {status}: `Success` is not one of ["new","pending","processing","accepted","captured","completed","cancelled","error","expired"] in GingerPluginSdk\Properties\Status->validateEnum() (line 16 of modules/contrib/custom_drupal_commerce/vendor/gingerpayments/ginger-plugin-sdk/src/Helpers/FieldsValidatorTrait.php).`

It's happening with iDeal orders. 
It seems that when converting from an array to an object, the order does not pass validation.

Here is payment_method_details of that order:
```
"payment_method_details": {
  "consumer_bic": "BANKNL3Y", "consumer_iban": "NL96SNSB0115541241",
  "consumer_name": "Hr E G H K\u00fcppers en/of MW M.J. K\u00fcppers-Veeneman",
  "issuer_id": "BANKNL3Y",
  "status": "Success",
  "transaction_id": "0030000122850944"},
```
They have `"status": "Success"` which does not pass status validation

Credit-Card orders do not have this problem and work fine

**Comment by tiutiunnykleasoft** [comment]
Resolved `9088dea53e2b50241fdbec2255b6774726912d40`
